### ISSUE TITLE
 Unable to run solr-log4j-autoupdate.ps1 

### ISSUE THREAD

**Issue by Rashmi-nw** [avwolferen/Sitecore.Solr-log4j-mitigation#3]
Hi, 
When I try to run `solr-log4j-autoupdate.ps1` , 
I'm getting: 
![image](https://user-images.githubusercontent.com/56313357/148052707-e180ae66-122f-458b-92d8-993e3013b2ef.png)

On investigating, I see that $newVersion is set to "2.17.0" and 2.17.0 folder is now removed in https://dlcdn.apache.org/logging/log4j/

Could you update the $newVersion value to 2.17.1 please? I hope 2.17.1 contains the fix for log4j vulnerabilities

**Comment by avwolferen** [comment]
Thank you for filing this issue.

Going to fix this :)

Fixes in PR https://github.com/avwolferen/Sitecore.Solr-log4j-mitigation/pull/4

Best regards,
Alex

**Comment by avwolferen** [comment]
Hi @Rashmi-nw 

Can you execute the script in branch https://github.com/avwolferen/Sitecore.Solr-log4j-mitigation/tree/issue/hashissue and share the output? I'm interested in the hashes that you receive from the download.

Should quite similar to:

Please specify the drive-letter you have the root of solr (c, d, or any other drive-letter). This is the drive-letter where the solr is installed.: d
Looking for Solr on your d: drive... May take a while to find those...
Hash to validate against is 60F529405DBCA8BA80AFA50A4990F0F340A7AB04B3F001AC8009CA851AADA1B1EB0695D54566609BCD5A52F79BD539268049172BFCA27B5531739D1FE87470AC
Downloading https://archive.apache.org/dist/logging/log4j/2.17.1/apache-log4j-2.17.1-bin.zip
Verifying downloaded apache-log4j-2.17.1-bin.zip
SHA512 FileHash for D:\git\alex\Sitecore.Solr-log4j-mitigation\temp\apache-log4j-2.17.1-bin.zip is 60F529405DBCA8BA80AFA50A4990F0F340A7AB04B3F001AC8009CA851AADA1B1EB0695D54566609BCD5A52F79BD539268049172BFCA27B5531739D1FE87470AC
Download is verified and OK!
Unpacking downloaded apache-log4j-2.17.1-bin.zip
Everything is ready...
Starting to process d:\Solr\scsolr-8.8.2
Stopping service scsolr-8.8.2
Solr instance in d:\Solr\scsolr-8.8.2 looks good!
Prometheus in Solr  d:\Solr\scsolr-8.8.2 looks good!
Starting service scsolr-8.8.2
Done with SOLR scsolr-8.8.2 located in d:\Solr\scsolr-8.8.2

Thanks in advance.

**Comment by Rashmi-nw** [comment]
Hi @avwolferen , 
Here's the output : 
![image](https://user-images.githubusercontent.com/56313357/148102573-19e893e5-b204-4bf7-89ee-ad16cb6749ed.png)

**Comment by avwolferen** [comment]
Hi @Rashmi-nw

I see that you were not using the changed script in the branch I mentioned in the comments. For the sake of simplicity I completed a pull request to main. Can you fetch/pull the latest changes and run it again? It should also output the hash from Apache and the actual downloaded file. I have seen situations in the last two weeks where the downloaded archive from Apache had a different file hash because of network issues.

looking forward to your response.

**Comment by Rashmi-nw** [comment]
Hi @avwolferen , 
Here's the latest screenshot: 
![image](https://user-images.githubusercontent.com/56313357/148115431-5b70d791-2423-42b3-92e2-14a364f6fd47.png)

What happens when you run these two lines of code? 
$log2j = "https://archive.apache.org/dist/logging/log4j/2.17.1/apache-log4j-2.17.1-bin.zip"
$log2jHash = (Invoke-WebRequest -Uri "$($log2j).sha512").Content.Split(' ')[0].ToUpperInvariant()

![image](https://user-images.githubusercontent.com/56313357/148115716-f6b651a1-58d2-40f9-8d2d-b150b5a54424.png)

**Comment by avwolferen** [comment]
I see what is the real issue is... You are running this on a machine without Internet Explorer installed as a feature. I have added -UseBasicParsing to the calls on Invoke-WebRequest 

The script still works on my machine in several test scenario's, I am unable to test this without internet explorer installed.
